"""First-run setup wizard for Hi-EV.

This module checks whether the daemon is in a launch-ready state and writes a
valid `.env` file from the in-HUD setup wizard. It intentionally does not depend
on an LLM key being present, so the wizard can run before configuration is
complete.
"""

from __future__ import annotations

import json
import logging
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field, field_validator

from ev.config import Settings, get_settings

logger = logging.getLogger(__name__)

_ENV_TEMPLATE = """# Hi-EV configuration — generated by the setup wizard.
# Personal-only boundary: handles/domains that EV must never ingest (JSON array).
EV_BLOCKED_HANDLES={blocked_handles}
EV_BLOCKED_DOMAINS={blocked_domains}

# Local notes vault path.
EV_NOTES_PATH={notes_path}

# LLM provider and keys.
EV_LLM_PROVIDER={llm_provider}
EV_LLM_MODEL={llm_model}
{llm_key_lines}

# Optional: GitHub personal token for repo ingestion.
{github_token_line}

# Optional: Google integration (read-only).
EV_GOOGLE_ENABLED=false

# Background ingestion and alert loop.
EV_INGEST_INTERVAL_SEC=300
EV_ALERT_INTERVAL_SEC=900
EV_QUIET_START={quiet_start}
EV_QUIET_END={quiet_end}
EV_KILL_SWITCH=false

# Local voice pipeline.
EV_VOICE_ENABLED={voice_enabled}
EV_VOICE_STT_BACKEND={voice_stt_backend}
EV_VOICE_TTS_BACKEND={voice_tts_backend}

# Local repo paths (used by the work_on tool).
EV_ROBOCAD_PATH={robocad_path}
EV_LEARNINGROBOTICS_PATH={learningrobotics_path}
EV_HIEV_PATH={hiev_path}
"""


class SetupRequest(BaseModel):
    """Payload from the HUD setup wizard."""

    notes_path: str = Field(..., min_length=1)
    llm_provider: str = Field(default="nvidia")
    llm_model: str | None = None
    nvidia_api_key: str | None = None
    anthropic_api_key: str | None = None
    openai_api_key: str | None = None
    github_token: str | None = None
    blocked_handles: list[str] = Field(default_factory=list)
    blocked_domains: list[str] = Field(default_factory=list)
    quiet_start: str = Field(default="22:00")
    quiet_end: str = Field(default="08:00")
    robocad_path: str | None = None
    learningrobotics_path: str | None = None
    hiev_path: str | None = None
    voice_enabled: bool = Field(default=False)
    voice_stt_backend: str | None = Field(default=None)
    voice_tts_backend: str | None = Field(default=None)

    @field_validator("llm_provider")
    @classmethod
    def _valid_provider(cls, value: str) -> str:
        allowed = {"nvidia", "anthropic", "openai"}
        if value not in allowed:
            raise ValueError(f"llm_provider must be one of {allowed}")
        return value

    @field_validator("voice_stt_backend", "voice_tts_backend")
    @classmethod
    def _valid_voice_backend(cls, value: str | None) -> str | None:
        if value is None:
            return None
        stripped = value.strip()
        if not stripped:
            return None
        allowed_stt = {"faster_whisper", "mock"}
        allowed_tts = {"kokoro", "pyttsx3", "mock"}
        # Validate against the union so we can reuse the same validator for both
        # fields; the VoiceManager will fall back safely if a backend is missing.
        if stripped not in allowed_stt | allowed_tts:
            raise ValueError(
                f"voice backend must be one of {sorted(allowed_stt | allowed_tts)}"
            )
        return stripped


@dataclass
class SetupStatus:
    """Result of checking whether first-run setup is required."""

    needs_setup: bool
    env_exists: bool
    env_path: Path
    missing: list[str] = field(default_factory=list)
    message: str = ""
    python_ok: bool = False
    python_version: str | None = None
    python_path: str | None = None


PYTHON_MIN_VERSION = (3, 12)


def check_python_version() -> tuple[bool, str | None, str | None]:
    """Check whether a suitable Python interpreter is available.

    Returns `(ok, version_string, path)`.
    """
    candidates = ["python", "python3", "py"]
    for name in candidates:
        path = shutil.which(name)
        if path is None:
            continue
        try:
            output = subprocess.run(
                [path, "--version"],
                capture_output=True,
                text=True,
                timeout=10,
                check=False,
            )
            # `python --version` prints to stderr; `python3 --version` varies.
            text = (output.stdout + output.stderr).strip()
            match = re.search(r"Python\s+(\d+)\.(\d+)", text)
            if not match:
                continue
            major, minor = int(match.group(1)), int(match.group(2))
            version = f"{major}.{minor}"
            if (major, minor) >= PYTHON_MIN_VERSION:
                return True, version, path
            return False, version, path
        except Exception:  # noqa: BLE001
            logger.debug("Could not verify %s: skipping", name)
            continue
    return False, None, None


def _env_file_path(settings: Settings | None = None) -> Path:
    """Return the resolved `.env` file path.

    The desktop entry point stores `.env` in the EV app data directory so it
    survives upgrades and stays outside the install directory.
    """
    settings = settings or get_settings()
    if settings.env_file_path:
        return Path(settings.env_file_path)
    return settings.app_data_dir / ".env"


def _notes_path_default() -> str:
    """Return a sensible default notes path for the current platform."""
    return str(Path.home() / "notes")


def _default_repo_path(name: str) -> str | None:
    """Return a default sibling-repo path if it exists on disk."""
    candidate = Path.home() / "projects" / name
    if candidate.exists():
        return str(candidate)
    return None


def check_setup_status(settings: Settings | None = None) -> SetupStatus:
    """Inspect current configuration and decide if setup is needed."""
    settings = settings or get_settings()
    env_path = _env_file_path(settings)

    missing: list[str] = []
    if not env_path.exists():
        missing.append("env_file")

    # notes_path is the one field we always require.
    try:
        notes = Path(str(settings.notes_path))
        if not notes.exists():
            missing.append("notes_path")
    except Exception:  # noqa: BLE001
        missing.append("notes_path")

    # At least one LLM provider key is strongly recommended; treat as missing
    # only when no key is present at all.
    has_key = any(
        key is not None
        for key in (
            settings.nvidia_api_key,
            settings.anthropic_api_key,
            settings.openai_api_key,
        )
    )
    if not has_key:
        missing.append("llm_key")

    python_ok, python_version, python_path = check_python_version()
    if not python_ok:
        missing.append("python")

    needs_setup = bool(missing)
    return SetupStatus(
        needs_setup=needs_setup,
        env_exists=env_path.exists(),
        env_path=env_path,
        missing=missing,
        message=(
            "Welcome to Hi-EV. Complete setup to finish launching."
            if needs_setup
            else "Hi-EV is configured and ready."
        ),
        python_ok=python_ok,
        python_version=python_version,
        python_path=python_path,
    )


def _default_llm_model(provider: str) -> str:
    """Return the default model name for a provider."""
    defaults = {
        "nvidia": "meta/llama-3.2-11b-vision-instruct",
        "openai": "gpt-4o-mini",
        "anthropic": "claude-3-5-sonnet-20241022",
    }
    return defaults.get(provider, "meta/llama-3.2-11b-vision-instruct")


def _write_env_file(req: SetupRequest, env_path: Path) -> None:
    """Serialize a SetupRequest to a `.env` file at `env_path`."""
    env_path.parent.mkdir(parents=True, exist_ok=True)

    llm_key_lines = []
    if req.nvidia_api_key:
        llm_key_lines.append(f"EV_NVIDIA_API_KEY={req.nvidia_api_key}")
    if req.anthropic_api_key:
        llm_key_lines.append(f"EV_ANTHROPIC_API_KEY={req.anthropic_api_key}")
    if req.openai_api_key:
        llm_key_lines.append(f"EV_OPENAI_API_KEY={req.openai_api_key}")

    github_token_line = (
        f"EV_GITHUB_TOKEN={req.github_token}"
        if req.github_token
        else "# EV_GITHUB_TOKEN="
    )

    content = _ENV_TEMPLATE.format(
        blocked_handles=json.dumps(req.blocked_handles),
        blocked_domains=json.dumps(req.blocked_domains),
        notes_path=req.notes_path,
        llm_provider=req.llm_provider,
        llm_model=req.llm_model or _default_llm_model(req.llm_provider),
        llm_key_lines="\n".join(llm_key_lines) if llm_key_lines else "# No LLM key configured.",
        github_token_line=github_token_line,
        quiet_start=req.quiet_start,
        quiet_end=req.quiet_end,
        voice_enabled="true" if req.voice_enabled else "false",
        voice_stt_backend=req.voice_stt_backend or "",
        voice_tts_backend=req.voice_tts_backend or "",
        robocad_path=req.robocad_path or _default_repo_path("RoboCAD") or "",
        learningrobotics_path=req.learningrobotics_path or _default_repo_path("LearningRobotics") or "",
        hiev_path=req.hiev_path or _default_repo_path("Hi-EV") or "",
    )

    env_path.write_text(content, encoding="utf-8")


def apply_setup(req: SetupRequest, settings: Settings | None = None) -> dict[str, Any]:
    """Validate and persist a setup request, then return status.

    The caller is responsible for restarting the daemon so the new `.env`
    values are loaded.
    """
    settings = settings or get_settings()

    # Validate notes_path exists or can be created as a directory.
    notes = Path(req.notes_path)
    try:
        if not notes.exists():
            notes.mkdir(parents=True, exist_ok=True)
        if not notes.is_dir():
            raise ValueError(f"notes_path is not a directory: {req.notes_path}")
    except OSError as exc:
        raise ValueError(f"Could not create notes path: {req.notes_path} ({exc})") from exc

    env_path = _env_file_path(settings)
    _write_env_file(req, env_path)

    return {
        "success": True,
        "env_path": str(env_path),
        "restart_required": True,
        "message": "Configuration saved. Please restart Hi-EV to apply changes.",
    }


def _available_voice_backends(kind: str) -> list[str]:
    """Return the names of registered voice backends that can be imported.

    Mirrors the helper in ``ev.server.api`` but lives here so setup defaults
    can include available backends without creating an import cycle.
    """
    from ev.core import registry

    if kind == "stt":
        from ev.voice import stt as _stt_module  # noqa: F401
    elif kind == "tts":
        from ev.voice import tts as _tts_module  # noqa: F401

    names: list[str] = []
    for name in registry[kind].list():
        cls = registry[kind].get_class(name)
        try:
            # Backends that raise VoiceBackendError because of missing optional
            # dependencies are still listed, but unrelated ImportErrors are skipped.
            cls()
            names.append(name)
        except Exception as exc:  # noqa: BLE001
            from ev.voice.component import VoiceBackendError

            if isinstance(exc, VoiceBackendError):
                names.append(name)
    return sorted(names)



def get_setup_defaults() -> dict[str, Any]:
    """Return sensible defaults for the setup wizard form."""
    settings = get_settings()
    return {
        "notes_path": _notes_path_default(),
        "llm_provider": settings.llm_provider or "nvidia",
        "llm_model": settings.llm_model or _default_llm_model("nvidia"),
        "blocked_handles": [],
        "blocked_domains": [],
        "quiet_start": "22:00",
        "quiet_end": "08:00",
        "voice_enabled": settings.voice_enabled,
        "voice_stt_backend": settings.voice_stt_backend or "",
        "voice_tts_backend": settings.voice_tts_backend or "",
        "available_stt": _available_voice_backends("stt"),
        "available_tts": _available_voice_backends("tts"),
        "robocad_path": _default_repo_path("RoboCAD"),
        "learningrobotics_path": _default_repo_path("LearningRobotics"),
        "hiev_path": _default_repo_path("Hi-EV"),
    }
