"""First-run setup wizard for Hi-EV.

This module checks whether the daemon is in a launch-ready state and writes a
valid `.env` file from the in-HUD setup wizard. It intentionally does not depend
on an LLM key being present, so the wizard can run before configuration is
complete.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field, field_validator

from ev.config import Settings, get_settings

_ENV_TEMPLATE = """# Hi-EV configuration — generated by the setup wizard.
# Personal-only boundary: handles/domains that EV must never ingest (JSON array).
EV_BLOCKED_HANDLES={blocked_handles}
EV_BLOCKED_DOMAINS={blocked_domains}

# Local notes vault path.
EV_NOTES_PATH={notes_path}

# LLM provider and keys.
EV_LLM_PROVIDER={llm_provider}
EV_LLM_MODEL={llm_model}
{llm_key_lines}

# Optional: GitHub personal token for repo ingestion.
{github_token_line}

# Optional: Google integration (read-only).
EV_GOOGLE_ENABLED=false

# Background ingestion and alert loop.
EV_INGEST_INTERVAL_SEC=300
EV_ALERT_INTERVAL_SEC=900
EV_QUIET_START={quiet_start}
EV_QUIET_END={quiet_end}
EV_KILL_SWITCH=false

# Local repo paths (used by the work_on tool).
EV_ROBOCAD_PATH={robocad_path}
EV_LEARNINGROBOTICS_PATH={learningrobotics_path}
EV_HIEV_PATH={hiev_path}
"""


class SetupRequest(BaseModel):
    """Payload from the HUD setup wizard."""

    notes_path: str = Field(..., min_length=1)
    llm_provider: str = Field(default="nvidia")
    llm_model: str | None = None
    nvidia_api_key: str | None = None
    anthropic_api_key: str | None = None
    openai_api_key: str | None = None
    github_token: str | None = None
    blocked_handles: list[str] = Field(default_factory=list)
    blocked_domains: list[str] = Field(default_factory=list)
    quiet_start: str = Field(default="22:00")
    quiet_end: str = Field(default="08:00")
    robocad_path: str | None = None
    learningrobotics_path: str | None = None
    hiev_path: str | None = None

    @field_validator("llm_provider")
    @classmethod
    def _valid_provider(cls, value: str) -> str:
        allowed = {"nvidia", "anthropic", "openai"}
        if value not in allowed:
            raise ValueError(f"llm_provider must be one of {allowed}")
        return value


@dataclass
class SetupStatus:
    """Result of checking whether first-run setup is required."""

    needs_setup: bool
    env_exists: bool
    env_path: Path
    missing: list[str] = field(default_factory=list)
    message: str = ""


def _env_file_path(settings: Settings | None = None) -> Path:
    """Return the resolved `.env` file path.

    The desktop entry point stores `.env` in the EV app data directory so it
    survives upgrades and stays outside the install directory.
    """
    settings = settings or get_settings()
    if settings.env_file_path:
        return Path(settings.env_file_path)
    return settings.app_data_dir / ".env"


def _notes_path_default() -> str:
    """Return a sensible default notes path for the current platform."""
    return str(Path.home() / "notes")


def _default_repo_path(name: str) -> str | None:
    """Return a default sibling-repo path if it exists on disk."""
    candidate = Path.home() / "projects" / name
    if candidate.exists():
        return str(candidate)
    return None


def check_setup_status(settings: Settings | None = None) -> SetupStatus:
    """Inspect current configuration and decide if setup is needed."""
    settings = settings or get_settings()
    env_path = _env_file_path(settings)

    missing: list[str] = []
    if not env_path.exists():
        missing.append("env_file")

    # notes_path is the one field we always require.
    try:
        notes = Path(str(settings.notes_path))
        if not notes.exists():
            missing.append("notes_path")
    except Exception:  # noqa: BLE001
        missing.append("notes_path")

    # At least one LLM provider key is strongly recommended; treat as missing
    # only when no key is present at all.
    has_key = any(
        key is not None
        for key in (
            settings.nvidia_api_key,
            settings.anthropic_api_key,
            settings.openai_api_key,
        )
    )
    if not has_key:
        missing.append("llm_key")

    needs_setup = bool(missing)
    return SetupStatus(
        needs_setup=needs_setup,
        env_exists=env_path.exists(),
        env_path=env_path,
        missing=missing,
        message=(
            "Welcome to Hi-EV. Complete setup to finish launching."
            if needs_setup
            else "Hi-EV is configured and ready."
        ),
    )


def _default_llm_model(provider: str) -> str:
    """Return the default model name for a provider."""
    defaults = {
        "nvidia": "meta/llama-3.2-11b-vision-instruct",
        "openai": "gpt-4o-mini",
        "anthropic": "claude-3-5-sonnet-20241022",
    }
    return defaults.get(provider, "meta/llama-3.2-11b-vision-instruct")


def _write_env_file(req: SetupRequest, env_path: Path) -> None:
    """Serialize a SetupRequest to a `.env` file at `env_path`."""
    env_path.parent.mkdir(parents=True, exist_ok=True)

    llm_key_lines = []
    if req.nvidia_api_key:
        llm_key_lines.append(f"EV_NVIDIA_API_KEY={req.nvidia_api_key}")
    if req.anthropic_api_key:
        llm_key_lines.append(f"EV_ANTHROPIC_API_KEY={req.anthropic_api_key}")
    if req.openai_api_key:
        llm_key_lines.append(f"EV_OPENAI_API_KEY={req.openai_api_key}")

    github_token_line = (
        f"EV_GITHUB_TOKEN={req.github_token}"
        if req.github_token
        else "# EV_GITHUB_TOKEN="
    )

    content = _ENV_TEMPLATE.format(
        blocked_handles=json.dumps(req.blocked_handles),
        blocked_domains=json.dumps(req.blocked_domains),
        notes_path=req.notes_path,
        llm_provider=req.llm_provider,
        llm_model=req.llm_model or _default_llm_model(req.llm_provider),
        llm_key_lines="\n".join(llm_key_lines) if llm_key_lines else "# No LLM key configured.",
        github_token_line=github_token_line,
        quiet_start=req.quiet_start,
        quiet_end=req.quiet_end,
        robocad_path=req.robocad_path or _default_repo_path("RoboCAD") or "",
        learningrobotics_path=req.learningrobotics_path or _default_repo_path("LearningRobotics") or "",
        hiev_path=req.hiev_path or _default_repo_path("Hi-EV") or "",
    )

    env_path.write_text(content, encoding="utf-8")


def apply_setup(req: SetupRequest, settings: Settings | None = None) -> dict[str, Any]:
    """Validate and persist a setup request, then return status.

    The caller is responsible for restarting the daemon so the new `.env`
    values are loaded.
    """
    settings = settings or get_settings()

    # Validate notes_path exists or can be created as a directory.
    notes = Path(req.notes_path)
    try:
        if not notes.exists():
            notes.mkdir(parents=True, exist_ok=True)
        if not notes.is_dir():
            raise ValueError(f"notes_path is not a directory: {req.notes_path}")
    except OSError as exc:
        raise ValueError(f"Could not create notes path: {req.notes_path} ({exc})") from exc

    env_path = _env_file_path(settings)
    _write_env_file(req, env_path)

    return {
        "success": True,
        "env_path": str(env_path),
        "restart_required": True,
        "message": "Configuration saved. Please restart Hi-EV to apply changes.",
    }


def get_setup_defaults() -> dict[str, Any]:
    """Return sensible defaults for the setup wizard form."""
    settings = get_settings()
    return {
        "notes_path": _notes_path_default(),
        "llm_provider": settings.llm_provider or "nvidia",
        "llm_model": settings.llm_model or _default_llm_model("nvidia"),
        "blocked_handles": [],
        "blocked_domains": [],
        "quiet_start": "22:00",
        "quiet_end": "08:00",
        "robocad_path": _default_repo_path("RoboCAD"),
        "learningrobotics_path": _default_repo_path("LearningRobotics"),
        "hiev_path": _default_repo_path("Hi-EV"),
    }
