"""add trusted flags to ingest and document_chunks

Revision ID: 3fdf19081353
Revises: e65cfe42f3a6
Create Date: 2026-09-19 12:10:36.783530

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3fdf19081353'
down_revision: str | None = 'e65cfe42f3a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('trusted', sa.Boolean(), nullable=True))
    op.add_column('ingest', sa.Column('trusted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingest', 'trusted')
    op.drop_column('document_chunks', 'trusted')
    # ### end Alembic commands ###
