"""add deadlines

Revision ID: aacdc9089a90
Revises: 
Create Date: 2026-09-15 11:50:30.674275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacdc9089a90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('snooze_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=512), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=True),
    sa.Column('last_reminded', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uix_deadline_source_id')
    )
    op.create_index(op.f('ix_deadlines_project_name'), 'deadlines', ['project_name'], unique=False)
    op.create_index(op.f('ix_deadlines_source'), 'deadlines', ['source'], unique=False)
    op.create_table('ingest',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('project_tag', sa.String(length=128), nullable=True),
    sa.Column('privacy_level', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uix_ingest_source_id')
    )
    op.create_index(op.f('ix_ingest_content_hash'), 'ingest', ['content_hash'], unique=False)
    op.create_index(op.f('ix_ingest_project_tag'), 'ingest', ['project_tag'], unique=False)
    op.create_index(op.f('ix_ingest_source'), 'ingest', ['source'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('repo_url', sa.String(length=512), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('current_phase', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('repo_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_ingest_source'), table_name='ingest')
    op.drop_index(op.f('ix_ingest_project_tag'), table_name='ingest')
    op.drop_index(op.f('ix_ingest_content_hash'), table_name='ingest')
    op.drop_table('ingest')
    op.drop_index(op.f('ix_deadlines_source'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_project_name'), table_name='deadlines')
    op.drop_table('deadlines')
    # ### end Alembic commands ###
